/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;    

/**
 *
 * @author Bruk
 */
public class InventoryManager extends javax.swing.JFrame {
    private JFrame frame;
    
    /**
     * Creates new form InventoryManager
     */
    public InventoryManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jcmbiPaymentMethod = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcmbiProduct = new javax.swing.JComboBox<>();
        jlblProductCode = new javax.swing.JLabel();
        jlblPricePerUnit = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtQuantity = new javax.swing.JTextField();
        jlblDate = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jcmbiDiscount = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlblTax = new javax.swing.JLabel();
        jlblSubTotal = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Payment Method");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jcmbiPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Payment Method", "Cash", "Visa", "Master Card" }));
        jPanel1.add(jcmbiPaymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 220, 70));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Product Discription");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Product Code");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Price Per Unit");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Date");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jcmbiProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Product", "Milk", "Yoghurt", "Chocolate", "Egg", "Water", "Soft Drink", "Detergent", "Wine", " " }));
        jcmbiProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbiProductActionPerformed(evt);
            }
        });
        jPanel2.add(jcmbiProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 120, -1));

        jlblProductCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jlblProductCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 90, 20));

        jlblPricePerUnit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jlblPricePerUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 80, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Quantity");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 70, -1));

        jtxtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtQuantityActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 80, -1));

        jlblDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jlblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 130, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 460, 150));

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Discount");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jcmbiDiscount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "5", "10", "15", "20" }));
        jPanel3.add(jcmbiDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 90, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 230, 70));

        jPanel4.setBackground(new java.awt.Color(102, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Tax");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Sub Total");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Total");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jlblTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jlblTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 20));

        jlblSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jlblSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 100, 20));

        jlblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jlblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 100, 20));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 460, 70));

        jPanel5.setBackground(new java.awt.Color(102, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, 250));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 370, 270));

        jPanel6.setBackground(new java.awt.Color(255, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, 40));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 40));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 300, 60));

        jPanel7.setBackground(new java.awt.Color(51, 0, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Inventory Manegement System");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 540, 60));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 840, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Inventory System"
        , JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION ){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   jlblProductCode.setText(null);
   jlblPricePerUnit.setText(null);
   jlblTax.setText(null);
   jlblSubTotal.setText(null);
   jlblTotal.setText(null);
   jcmbiProduct.setSelectedIndex(0);
   jcmbiDiscount.setSelectedIndex(0);
   jcmbiPaymentMethod.setSelectedIndex(0);
   DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
   LocalDateTime now = LocalDateTime.now();
   jlblDate.setText(dtf.format(now));
   jtxtQuantity.setText("0");
   jtxtReceipt.setText(null);
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jcmbiProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbiProductActionPerformed
           if(jcmbiProduct.getSelectedItem().equals("Milk")){
               jlblProductCode.setText("MIL10");
               jlblPricePerUnit.setText("25");
           }
           else if(jcmbiProduct.getSelectedItem().equals("Yoghurt")){
               jlblProductCode.setText("YOG10");
               jlblPricePerUnit.setText("30");
           }
           else if(jcmbiProduct.getSelectedItem().equals("Chocolate")){
               jlblProductCode.setText("CHO321");
               jlblPricePerUnit.setText("50");
           }
           else if(jcmbiProduct.getSelectedItem().equals("Egg")){
               jlblProductCode.setText("EG21");
               jlblPricePerUnit.setText("7");
           }
           else if(jcmbiProduct.getSelectedItem().equals("Water")){
               jlblProductCode.setText("WAT111");
               jlblPricePerUnit.setText("15");
           }
           else if(jcmbiProduct.getSelectedItem().equals("Soft Drink")){
               jlblProductCode.setText("SOD741");
               jlblPricePerUnit.setText("25");
           }
           else if(jcmbiProduct.getSelectedItem().equals("Detergent")){
               jlblProductCode.setText("DET1");
               jlblPricePerUnit.setText("45");
           }
           else if(jcmbiProduct.getSelectedItem().equals("Wine")){
               jlblProductCode.setText("WIE21");
               jlblPricePerUnit.setText("400");
           }
    }//GEN-LAST:event_jcmbiProductActionPerformed

    private void jtxtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtQuantityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jtxtReceipt.setText(null);
        double Discount, SubTotal, Tax, Total;
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        jlblDate.setText(dtf.format(now));
        
        double PricePerUnit = Double.parseDouble(jlblPricePerUnit.getText());
        
        double Quantity = Double.parseDouble(jtxtQuantity.getText());
        
        Object NoDiscount = jcmbiDiscount.getSelectedItem();
        String ApproveDiscount = NoDiscount.toString();
        double StatedDiscount = Double.parseDouble(ApproveDiscount);
        
        Discount = ((PricePerUnit * Quantity)* StatedDiscount)/100; //Calculating discount
        SubTotal = ((PricePerUnit * Quantity) - Discount); //Calculating Sub total
        Tax = SubTotal * 0.15; // Calculating Vat
        Total = (Tax + SubTotal);
        
        //Entering The value to Total
        
        String iSubT = String.format("ETB %.2f", SubTotal);
        jlblSubTotal.setText(iSubT);
        
        String iTax = String.format("ETB %.2f", Tax);
        jlblTax.setText(iTax);
        
        String iTot = String.format("ETB %.2f", Total);
        jlblTotal.setText(iTot);
        
        // Receipt
        
        //double qty1 = Double.parseDouble(jlblPricePerUnit.getText());
        //double qty2 = Double.parseDouble(jtxtQuantity.getText());
        String qty3 = (jlblProductCode.getText());
        String qty4 = (jlblDate.getText()); 
        
        jtxtReceipt.append("\tZemen Super Market\n\n" + "\n\t\tDate: " + qty4  
                + "\n   Product Code: \t\t" + qty3 + "\n   Quantity: \t\t\t"
                + Quantity + "\n   Price Per Unit: \t\t" +
                PricePerUnit + "\n\n   Tax: \t\t\t" + iTax +
                 "\n   Sub Total: \t\t\t" + iSubT +
                "\n\n" + "   Total:\t\t\t" + iTot + "\n\n\t Please keep the reciept for your record");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcmbiDiscount;
    private javax.swing.JComboBox<String> jcmbiPaymentMethod;
    private javax.swing.JComboBox<String> jcmbiProduct;
    private javax.swing.JLabel jlblDate;
    private javax.swing.JLabel jlblPricePerUnit;
    private javax.swing.JLabel jlblProductCode;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JTextField jtxtQuantity;
    private javax.swing.JTextArea jtxtReceipt;
    // End of variables declaration//GEN-END:variables
}
